# This is a basic workflow to help you get started with Actions

name: ReadyAPI Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Install-and-Run-ReadyAPI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - uses: actions/checkout@v1

      - name: create downloads folder
        run: |
         mkdir -p ~/Downloads
      
      - name: Download ReadyAPI installer
        run: curl https://dl.eviware.com/ready-api/3.59.0/ReadyAPI-x64-3.59.0.sh -o ~/Downloads/ReadyAPI-x64-3.59.0.sh

      # View the contents of the new Downloads folder and the ReadyAPI installer
      - name: List directory contents recursively on Ubuntu
        run: |
         ls -la ~/Downloads

      - name: Make installer executable
        run: chmod +x ~/Downloads/ReadyAPI-x64-3.59.0.sh
  
      - name: Install ReadyAPI
        run: ~/Downloads/ReadyAPI-x64-3.59.0.sh -q

      # View the contents of the Smartbear installation and the location of the testrunner script
      - name: List directory contents of Smartbear installation
        run: |
         ls -la ~/SmartBear/ReadyAPI-3.59.0/bin
   
      # execute ReadyAPI project by running testrunner script. The ./ references the ReadyAPI project stored in the git repo.  
      - name: execute the ReadyAPI project stored in repository
        run: | 
          ~/SmartBear/ReadyAPI-3.59.0/bin/testrunner.sh "-RJUnit-Style HTML Report" -FXML -accessKey "03c35bd2-9362-44ea-b378-c4e30dd09914" "-EDefault environment" ./
